### ISSUE TITLE
Unable to assign class ASProgressPopUpView to UIProgressView in swift 3 Xcode 8

### ISSUE THREAD

**Issue by hslightnin** [alskipp/ASProgressPopUpView#12]

**Comment by alskipp** [comment]
I think I should have pointed out the change in class hierarchy when this update was introduced! The latest version is a subclass of `UIView` rather than `UIProgressView`. 

If you need to maintain the previous class hierarchy then you can use this branch instead:
https://github.com/alskipp/ASProgressPopUpView/tree/UIProgressView-subclass

**Comment by hslightnin** [comment]
I set it to UIVew, but the bar doesn't appear, what else is needed to set it up?

**Comment by alskipp** [comment]
Interface builder won't show the bar (as it's subclassed from UIView) but it should appear when you run the app?

I'll have to look into `IBDesignable` at some point so that interface builder displays the bar.

**Comment by hslightnin** [comment]
ok i got it, thanks!

**Comment by alskipp** [comment]
Glad it's working for you. I'll update the `README` about the changes.
