### ISSUE TITLE
Resize Progress Bar

### ISSUE THREAD

**Issue by YingshanDeng** [alskipp/ASProgressPopUpView#6]
How to Resize Progress Bar? Especially height。

**Comment by alskipp** [comment]
If you increase the font size you use, the height of the pop-up should increase to fit the text. Is this what you need?

**Comment by YingshanDeng** [comment]
Oh, NO. I just want to increase the height of the progress bar which under the pop-up view. In StackOverflow,I found the answer : http://stackoverflow.com/a/21041670 . Howerer, the left and right ends view is diff. (The progress bar is rounded corner default, but I want it without rounded corner.)

![d6ed70e7-4ea3-46a4-8894-d433ccb66e37](https://cloud.githubusercontent.com/assets/7246595/6996909/268fae84-dbd7-11e4-91a2-ad463522a1c0.png)

**Comment by alskipp** [comment]
I'm not sure what the best suggestion would be. As far as I'm aware there isn't a way to define a custom path for the track, though you can supply a custom image (but you'd then lose the ability to constantly update the track color).

The ability to change the size of the track is not something I'm planning on adding to the component, as I'm unaware of a clean way of implementing such functionality. It might require starting from scratch with a custom control, rather than subclassing UIProgressView?

Best of luck (if you do find a good way of achieving this, then do post a comment explaining the method).

Al

**Comment by alskipp** [comment]
Hi @YingshanDeng please take a look at this feature branch:
https://github.com/alskipp/ASProgressPopUpView/tree/uiview_subclass

This is very much work in progress. For further discussion, please refer to issue #7

Cheers,
Al
